power<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
subsetpower <- subset(power,power$Date =="1/2/2007" | power$Date == "2/2/2007")
datetime <- strptime(paste(subsetpower$Date, subsetpower$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(as.character(subsetpower$Global_active_power))
plot(datetime, globalActivePower, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()