power<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
subsetpower <- subset(power,power$Date =="1/2/2007" | power$Date == "2/2/2007")
hist(as.numeric(as.character(subsetpower$Global_active_power)),col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()